name: Run Tubi Scraper
permissions:
  contents: write

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4hours
  workflow_dispatch:      # Allows manual triggering

jobs:
  scrape-tubi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 urllib3 pysocks

      - name: Remove old files
        run: |
          rm -f tubi_playlist.m3u tubi_epg.xml
          echo "Removed old files (if they existed)"

      - name: Run tubi_scraper.py
        run: python tubi_scraper.py
        shell: /usr/bin/bash -e {0}
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.13.2/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.13.2/x64/lib

      - name: Debug files and commit
        run: |
          echo "Current directory: $(/bin/pwd)"
          ls -l
          git status
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tubi_playlist.m3u tubi_epg.xml
          echo "Files staged:"
          git status
          git commit -m "Update Tubi playlist and EPG files - $(date -u +'%Y-%m-%d %H:%M UTC')" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
